spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/securitydb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
#  security:
#    user:
#      name: Wilson
#      password: 123qwe